resourcePackages:
- com.contractreview.rest
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Contract Review
    description: 'This is a sample server for Contract Review'
    termsOfService: http://www.apache.org/licenses/LICENSE-2.0.html
    contact:
      email: joserene.campa@gmail.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html